//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPunter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectPunterEntities : DbContext
    {
        public ProjectPunterEntities()
            : base("name=ProjectPunterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_country> tb_country { get; set; }
        public virtual DbSet<tb_horse> tb_horse { get; set; }
        public virtual DbSet<tb_class> tb_class { get; set; }
        public virtual DbSet<tb_event> tb_event { get; set; }
        public virtual DbSet<tb_jockey> tb_jockey { get; set; }
        public virtual DbSet<tb_race> tb_race { get; set; }
        public virtual DbSet<tb_race_horse> tb_race_horse { get; set; }
        public virtual DbSet<tb_racetype> tb_racetype { get; set; }
        public virtual DbSet<tb_surface> tb_surface { get; set; }
        public virtual DbSet<tb_trainer> tb_trainer { get; set; }
        public virtual DbSet<tb_weather> tb_weather { get; set; }
    
        public virtual int pr_add_horse(string horse_Name, Nullable<System.DateTime> date_Of_Birth, Nullable<int> country)
        {
            var horse_NameParameter = horse_Name != null ?
                new ObjectParameter("Horse_Name", horse_Name) :
                new ObjectParameter("Horse_Name", typeof(string));
    
            var date_Of_BirthParameter = date_Of_Birth.HasValue ?
                new ObjectParameter("Date_Of_Birth", date_Of_Birth) :
                new ObjectParameter("Date_Of_Birth", typeof(System.DateTime));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_add_horse", horse_NameParameter, date_Of_BirthParameter, countryParameter);
        }
    
        public virtual ObjectResult<pr_get_countries_Result> pr_get_countries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_countries_Result>("pr_get_countries");
        }
    }
}
