//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_horse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_horse()
        {
            this.tb_race_horse = new HashSet<tb_race_horse>();
        }
    
        public int Horse_Id { get; set; }
        public string Horse_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public bool IsRetired { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual tb_country tb_country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_race_horse> tb_race_horse { get; set; }
    }
}
