//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_jockey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_jockey()
        {
            this.tb_race_horse = new HashSet<tb_race_horse>();
        }
    
        public int Jockey_Id { get; set; }
        public string Jockey_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_race_horse> tb_race_horse { get; set; }
    }
}
