//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_racetype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_racetype()
        {
            this.tb_race = new HashSet<tb_race>();
        }
    
        public int Race_Type_Id { get; set; }
        public string Race_Type_Description { get; set; }
        public bool Hurdle { get; set; }
        public Nullable<int> No_Of_Hurdles { get; set; }
        public int Meters { get; set; }
        public int furlongs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_race> tb_race { get; set; }
    }
}
