//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_race()
        {
            this.tb_race_horse = new HashSet<tb_race_horse>();
        }
    
        public int Race_Id { get; set; }
        public int Number_Of_Horses { get; set; }
        public bool IsComplete { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tb_class tb_class { get; set; }
        public virtual tb_event tb_event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_race_horse> tb_race_horse { get; set; }
        public virtual tb_racetype tb_racetype { get; set; }
        public virtual tb_surface tb_surface { get; set; }
        public virtual tb_weather tb_weather { get; set; }
    }
}
