//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_race_horse
    {
        public int Race_Id { get; set; }
        public int Horse_Id { get; set; }
        public int Weight { get; set; }
        public int Age { get; set; }
        public int Trainer_Id { get; set; }
        public int Jockey_Id { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> DNF { get; set; }
        public Nullable<bool> Clean_Race { get; set; }
    
        public virtual tb_horse tb_horse { get; set; }
        public virtual tb_jockey tb_jockey { get; set; }
        public virtual tb_race tb_race { get; set; }
        public virtual tb_trainer tb_trainer { get; set; }
    }
}
